/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthedOrganizationSlugRouteRouteImport } from './routes/_authed/$organizationSlug/route'
import { Route as AuthedOnboardingIndexRouteImport } from './routes/_authed/onboarding/index'
import { Route as AuthedOrganizationSlugIndexRouteImport } from './routes/_authed/$organizationSlug/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as AuthedInviteInvitationIdRouteImport } from './routes/_authed/invite/$invitationId'
import { Route as AuthedOrganizationSlugProjectSlugRouteRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/route'
import { Route as AuthedOrganizationSlugProjectSlugIndexRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/index'
import { Route as AuthedOrganizationSlugSettingsTeamRouteImport } from './routes/_authed/$organizationSlug/settings/team'
import { Route as AuthedOrganizationSlugProjectSlugSettingsRouteRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/route'
import { Route as AuthedOrganizationSlugProjectSlugStrategiesIndexRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/strategies/index'
import { Route as AuthedOrganizationSlugProjectSlugSettingsIndexRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/index'
import { Route as AuthedOrganizationSlugProjectSlugLinksIndexRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/links/index'
import { Route as AuthedOrganizationSlugProjectSlugContentIndexRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/content/index'
import { Route as AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/strategies/$strategyId'
import { Route as AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/writing-settings'
import { Route as AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/publishing-settings'
import { Route as AuthedOrganizationSlugProjectSlugSettingsProjectRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/project'
import { Route as AuthedOrganizationSlugProjectSlugSettingsImageSettingsRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/image-settings'
import { Route as AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/business-background'
import { Route as AuthedOrganizationSlugProjectSlugContentDraftIdRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/content/$draftId'
import { Route as AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRouteImport } from './routes/_authed/$organizationSlug/$projectSlug/settings/integrations/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrganizationSlugRouteRoute =
  AuthedOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOnboardingIndexRoute = AuthedOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedOrganizationSlugIndexRoute =
  AuthedOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrganizationSlugRouteRoute,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInviteInvitationIdRoute =
  AuthedInviteInvitationIdRouteImport.update({
    id: '/invite/$invitationId',
    path: '/invite/$invitationId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugRouteRoute =
  AuthedOrganizationSlugProjectSlugRouteRouteImport.update({
    id: '/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => AuthedOrganizationSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugIndexRoute =
  AuthedOrganizationSlugProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugSettingsTeamRoute =
  AuthedOrganizationSlugSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthedOrganizationSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugSettingsRouteRoute =
  AuthedOrganizationSlugProjectSlugSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugStrategiesIndexRoute =
  AuthedOrganizationSlugProjectSlugStrategiesIndexRouteImport.update({
    id: '/strategies/',
    path: '/strategies/',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugSettingsIndexRoute =
  AuthedOrganizationSlugProjectSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugSettingsRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugLinksIndexRoute =
  AuthedOrganizationSlugProjectSlugLinksIndexRouteImport.update({
    id: '/links/',
    path: '/links/',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugContentIndexRoute =
  AuthedOrganizationSlugProjectSlugContentIndexRouteImport.update({
    id: '/content/',
    path: '/content/',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute =
  AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRouteImport.update({
    id: '/strategies/$strategyId',
    path: '/strategies/$strategyId',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute =
  AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRouteImport.update({
    id: '/writing-settings',
    path: '/writing-settings',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugSettingsRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute =
  AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRouteImport.update(
    {
      id: '/publishing-settings',
      path: '/publishing-settings',
      getParentRoute: () => AuthedOrganizationSlugProjectSlugSettingsRouteRoute,
    } as any,
  )
const AuthedOrganizationSlugProjectSlugSettingsProjectRoute =
  AuthedOrganizationSlugProjectSlugSettingsProjectRouteImport.update({
    id: '/project',
    path: '/project',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugSettingsRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute =
  AuthedOrganizationSlugProjectSlugSettingsImageSettingsRouteImport.update({
    id: '/image-settings',
    path: '/image-settings',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugSettingsRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute =
  AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRouteImport.update(
    {
      id: '/business-background',
      path: '/business-background',
      getParentRoute: () => AuthedOrganizationSlugProjectSlugSettingsRouteRoute,
    } as any,
  )
const AuthedOrganizationSlugProjectSlugContentDraftIdRoute =
  AuthedOrganizationSlugProjectSlugContentDraftIdRouteImport.update({
    id: '/content/$draftId',
    path: '/content/$draftId',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugRouteRoute,
  } as any)
const AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute =
  AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthedOrganizationSlugProjectSlugSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$organizationSlug': typeof AuthedOrganizationSlugRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/$organizationSlug/$projectSlug': typeof AuthedOrganizationSlugProjectSlugRouteRouteWithChildren
  '/invite/$invitationId': typeof AuthedInviteInvitationIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/$organizationSlug/': typeof AuthedOrganizationSlugIndexRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
  '/$organizationSlug/$projectSlug/settings': typeof AuthedOrganizationSlugProjectSlugSettingsRouteRouteWithChildren
  '/$organizationSlug/settings/team': typeof AuthedOrganizationSlugSettingsTeamRoute
  '/$organizationSlug/$projectSlug/': typeof AuthedOrganizationSlugProjectSlugIndexRoute
  '/$organizationSlug/$projectSlug/content/$draftId': typeof AuthedOrganizationSlugProjectSlugContentDraftIdRoute
  '/$organizationSlug/$projectSlug/settings/business-background': typeof AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute
  '/$organizationSlug/$projectSlug/settings/image-settings': typeof AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute
  '/$organizationSlug/$projectSlug/settings/project': typeof AuthedOrganizationSlugProjectSlugSettingsProjectRoute
  '/$organizationSlug/$projectSlug/settings/publishing-settings': typeof AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute
  '/$organizationSlug/$projectSlug/settings/writing-settings': typeof AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute
  '/$organizationSlug/$projectSlug/strategies/$strategyId': typeof AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute
  '/$organizationSlug/$projectSlug/content': typeof AuthedOrganizationSlugProjectSlugContentIndexRoute
  '/$organizationSlug/$projectSlug/links': typeof AuthedOrganizationSlugProjectSlugLinksIndexRoute
  '/$organizationSlug/$projectSlug/settings/': typeof AuthedOrganizationSlugProjectSlugSettingsIndexRoute
  '/$organizationSlug/$projectSlug/strategies': typeof AuthedOrganizationSlugProjectSlugStrategiesIndexRoute
  '/$organizationSlug/$projectSlug/settings/integrations': typeof AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$invitationId': typeof AuthedInviteInvitationIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/$organizationSlug': typeof AuthedOrganizationSlugIndexRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
  '/$organizationSlug/settings/team': typeof AuthedOrganizationSlugSettingsTeamRoute
  '/$organizationSlug/$projectSlug': typeof AuthedOrganizationSlugProjectSlugIndexRoute
  '/$organizationSlug/$projectSlug/content/$draftId': typeof AuthedOrganizationSlugProjectSlugContentDraftIdRoute
  '/$organizationSlug/$projectSlug/settings/business-background': typeof AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute
  '/$organizationSlug/$projectSlug/settings/image-settings': typeof AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute
  '/$organizationSlug/$projectSlug/settings/project': typeof AuthedOrganizationSlugProjectSlugSettingsProjectRoute
  '/$organizationSlug/$projectSlug/settings/publishing-settings': typeof AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute
  '/$organizationSlug/$projectSlug/settings/writing-settings': typeof AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute
  '/$organizationSlug/$projectSlug/strategies/$strategyId': typeof AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute
  '/$organizationSlug/$projectSlug/content': typeof AuthedOrganizationSlugProjectSlugContentIndexRoute
  '/$organizationSlug/$projectSlug/links': typeof AuthedOrganizationSlugProjectSlugLinksIndexRoute
  '/$organizationSlug/$projectSlug/settings': typeof AuthedOrganizationSlugProjectSlugSettingsIndexRoute
  '/$organizationSlug/$projectSlug/strategies': typeof AuthedOrganizationSlugProjectSlugStrategiesIndexRoute
  '/$organizationSlug/$projectSlug/settings/integrations': typeof AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/$organizationSlug': typeof AuthedOrganizationSlugRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/_authed/$organizationSlug/$projectSlug': typeof AuthedOrganizationSlugProjectSlugRouteRouteWithChildren
  '/_authed/invite/$invitationId': typeof AuthedInviteInvitationIdRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_authed/$organizationSlug/': typeof AuthedOrganizationSlugIndexRoute
  '/_authed/onboarding/': typeof AuthedOnboardingIndexRoute
  '/_authed/$organizationSlug/$projectSlug/settings': typeof AuthedOrganizationSlugProjectSlugSettingsRouteRouteWithChildren
  '/_authed/$organizationSlug/settings/team': typeof AuthedOrganizationSlugSettingsTeamRoute
  '/_authed/$organizationSlug/$projectSlug/': typeof AuthedOrganizationSlugProjectSlugIndexRoute
  '/_authed/$organizationSlug/$projectSlug/content/$draftId': typeof AuthedOrganizationSlugProjectSlugContentDraftIdRoute
  '/_authed/$organizationSlug/$projectSlug/settings/business-background': typeof AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute
  '/_authed/$organizationSlug/$projectSlug/settings/image-settings': typeof AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute
  '/_authed/$organizationSlug/$projectSlug/settings/project': typeof AuthedOrganizationSlugProjectSlugSettingsProjectRoute
  '/_authed/$organizationSlug/$projectSlug/settings/publishing-settings': typeof AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute
  '/_authed/$organizationSlug/$projectSlug/settings/writing-settings': typeof AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute
  '/_authed/$organizationSlug/$projectSlug/strategies/$strategyId': typeof AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute
  '/_authed/$organizationSlug/$projectSlug/content/': typeof AuthedOrganizationSlugProjectSlugContentIndexRoute
  '/_authed/$organizationSlug/$projectSlug/links/': typeof AuthedOrganizationSlugProjectSlugLinksIndexRoute
  '/_authed/$organizationSlug/$projectSlug/settings/': typeof AuthedOrganizationSlugProjectSlugSettingsIndexRoute
  '/_authed/$organizationSlug/$projectSlug/strategies/': typeof AuthedOrganizationSlugProjectSlugStrategiesIndexRoute
  '/_authed/$organizationSlug/$projectSlug/settings/integrations/': typeof AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$organizationSlug'
    | '/api/$'
    | '/$organizationSlug/$projectSlug'
    | '/invite/$invitationId'
    | '/api/rpc/$'
    | '/$organizationSlug/'
    | '/onboarding'
    | '/$organizationSlug/$projectSlug/settings'
    | '/$organizationSlug/settings/team'
    | '/$organizationSlug/$projectSlug/'
    | '/$organizationSlug/$projectSlug/content/$draftId'
    | '/$organizationSlug/$projectSlug/settings/business-background'
    | '/$organizationSlug/$projectSlug/settings/image-settings'
    | '/$organizationSlug/$projectSlug/settings/project'
    | '/$organizationSlug/$projectSlug/settings/publishing-settings'
    | '/$organizationSlug/$projectSlug/settings/writing-settings'
    | '/$organizationSlug/$projectSlug/strategies/$strategyId'
    | '/$organizationSlug/$projectSlug/content'
    | '/$organizationSlug/$projectSlug/links'
    | '/$organizationSlug/$projectSlug/settings/'
    | '/$organizationSlug/$projectSlug/strategies'
    | '/$organizationSlug/$projectSlug/settings/integrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/$'
    | '/invite/$invitationId'
    | '/api/rpc/$'
    | '/$organizationSlug'
    | '/onboarding'
    | '/$organizationSlug/settings/team'
    | '/$organizationSlug/$projectSlug'
    | '/$organizationSlug/$projectSlug/content/$draftId'
    | '/$organizationSlug/$projectSlug/settings/business-background'
    | '/$organizationSlug/$projectSlug/settings/image-settings'
    | '/$organizationSlug/$projectSlug/settings/project'
    | '/$organizationSlug/$projectSlug/settings/publishing-settings'
    | '/$organizationSlug/$projectSlug/settings/writing-settings'
    | '/$organizationSlug/$projectSlug/strategies/$strategyId'
    | '/$organizationSlug/$projectSlug/content'
    | '/$organizationSlug/$projectSlug/links'
    | '/$organizationSlug/$projectSlug/settings'
    | '/$organizationSlug/$projectSlug/strategies'
    | '/$organizationSlug/$projectSlug/settings/integrations'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/$organizationSlug'
    | '/api/$'
    | '/_authed/$organizationSlug/$projectSlug'
    | '/_authed/invite/$invitationId'
    | '/api/rpc/$'
    | '/_authed/$organizationSlug/'
    | '/_authed/onboarding/'
    | '/_authed/$organizationSlug/$projectSlug/settings'
    | '/_authed/$organizationSlug/settings/team'
    | '/_authed/$organizationSlug/$projectSlug/'
    | '/_authed/$organizationSlug/$projectSlug/content/$draftId'
    | '/_authed/$organizationSlug/$projectSlug/settings/business-background'
    | '/_authed/$organizationSlug/$projectSlug/settings/image-settings'
    | '/_authed/$organizationSlug/$projectSlug/settings/project'
    | '/_authed/$organizationSlug/$projectSlug/settings/publishing-settings'
    | '/_authed/$organizationSlug/$projectSlug/settings/writing-settings'
    | '/_authed/$organizationSlug/$projectSlug/strategies/$strategyId'
    | '/_authed/$organizationSlug/$projectSlug/content/'
    | '/_authed/$organizationSlug/$projectSlug/links/'
    | '/_authed/$organizationSlug/$projectSlug/settings/'
    | '/_authed/$organizationSlug/$projectSlug/strategies/'
    | '/_authed/$organizationSlug/$projectSlug/settings/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$organizationSlug': {
      id: '/_authed/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/$organizationSlug'
      preLoaderRoute: typeof AuthedOrganizationSlugRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/onboarding/': {
      id: '/_authed/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/$organizationSlug/': {
      id: '/_authed/$organizationSlug/'
      path: '/'
      fullPath: '/$organizationSlug/'
      preLoaderRoute: typeof AuthedOrganizationSlugIndexRouteImport
      parentRoute: typeof AuthedOrganizationSlugRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/invite/$invitationId': {
      id: '/_authed/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof AuthedInviteInvitationIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug': {
      id: '/_authed/$organizationSlug/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$organizationSlug/$projectSlug'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugRouteRouteImport
      parentRoute: typeof AuthedOrganizationSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/': {
      id: '/_authed/$organizationSlug/$projectSlug/'
      path: '/'
      fullPath: '/$organizationSlug/$projectSlug/'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugIndexRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteRoute
    }
    '/_authed/$organizationSlug/settings/team': {
      id: '/_authed/$organizationSlug/settings/team'
      path: '/settings/team'
      fullPath: '/$organizationSlug/settings/team'
      preLoaderRoute: typeof AuthedOrganizationSlugSettingsTeamRouteImport
      parentRoute: typeof AuthedOrganizationSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings': {
      id: '/_authed/$organizationSlug/$projectSlug/settings'
      path: '/settings'
      fullPath: '/$organizationSlug/$projectSlug/settings'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/strategies/': {
      id: '/_authed/$organizationSlug/$projectSlug/strategies/'
      path: '/strategies'
      fullPath: '/$organizationSlug/$projectSlug/strategies'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugStrategiesIndexRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings/': {
      id: '/_authed/$organizationSlug/$projectSlug/settings/'
      path: '/'
      fullPath: '/$organizationSlug/$projectSlug/settings/'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsIndexRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/links/': {
      id: '/_authed/$organizationSlug/$projectSlug/links/'
      path: '/links'
      fullPath: '/$organizationSlug/$projectSlug/links'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugLinksIndexRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/content/': {
      id: '/_authed/$organizationSlug/$projectSlug/content/'
      path: '/content'
      fullPath: '/$organizationSlug/$projectSlug/content'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugContentIndexRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/strategies/$strategyId': {
      id: '/_authed/$organizationSlug/$projectSlug/strategies/$strategyId'
      path: '/strategies/$strategyId'
      fullPath: '/$organizationSlug/$projectSlug/strategies/$strategyId'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings/writing-settings': {
      id: '/_authed/$organizationSlug/$projectSlug/settings/writing-settings'
      path: '/writing-settings'
      fullPath: '/$organizationSlug/$projectSlug/settings/writing-settings'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings/publishing-settings': {
      id: '/_authed/$organizationSlug/$projectSlug/settings/publishing-settings'
      path: '/publishing-settings'
      fullPath: '/$organizationSlug/$projectSlug/settings/publishing-settings'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings/project': {
      id: '/_authed/$organizationSlug/$projectSlug/settings/project'
      path: '/project'
      fullPath: '/$organizationSlug/$projectSlug/settings/project'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsProjectRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings/image-settings': {
      id: '/_authed/$organizationSlug/$projectSlug/settings/image-settings'
      path: '/image-settings'
      fullPath: '/$organizationSlug/$projectSlug/settings/image-settings'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsImageSettingsRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings/business-background': {
      id: '/_authed/$organizationSlug/$projectSlug/settings/business-background'
      path: '/business-background'
      fullPath: '/$organizationSlug/$projectSlug/settings/business-background'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/content/$draftId': {
      id: '/_authed/$organizationSlug/$projectSlug/content/$draftId'
      path: '/content/$draftId'
      fullPath: '/$organizationSlug/$projectSlug/content/$draftId'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugContentDraftIdRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugRouteRoute
    }
    '/_authed/$organizationSlug/$projectSlug/settings/integrations/': {
      id: '/_authed/$organizationSlug/$projectSlug/settings/integrations/'
      path: '/integrations'
      fullPath: '/$organizationSlug/$projectSlug/settings/integrations'
      preLoaderRoute: typeof AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRouteImport
      parentRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRoute
    }
  }
}

interface AuthedOrganizationSlugProjectSlugSettingsRouteRouteChildren {
  AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute: typeof AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute
  AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute: typeof AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute
  AuthedOrganizationSlugProjectSlugSettingsProjectRoute: typeof AuthedOrganizationSlugProjectSlugSettingsProjectRoute
  AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute: typeof AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute
  AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute: typeof AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute
  AuthedOrganizationSlugProjectSlugSettingsIndexRoute: typeof AuthedOrganizationSlugProjectSlugSettingsIndexRoute
  AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute: typeof AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute
}

const AuthedOrganizationSlugProjectSlugSettingsRouteRouteChildren: AuthedOrganizationSlugProjectSlugSettingsRouteRouteChildren =
  {
    AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute:
      AuthedOrganizationSlugProjectSlugSettingsBusinessBackgroundRoute,
    AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute:
      AuthedOrganizationSlugProjectSlugSettingsImageSettingsRoute,
    AuthedOrganizationSlugProjectSlugSettingsProjectRoute:
      AuthedOrganizationSlugProjectSlugSettingsProjectRoute,
    AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute:
      AuthedOrganizationSlugProjectSlugSettingsPublishingSettingsRoute,
    AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute:
      AuthedOrganizationSlugProjectSlugSettingsWritingSettingsRoute,
    AuthedOrganizationSlugProjectSlugSettingsIndexRoute:
      AuthedOrganizationSlugProjectSlugSettingsIndexRoute,
    AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute:
      AuthedOrganizationSlugProjectSlugSettingsIntegrationsIndexRoute,
  }

const AuthedOrganizationSlugProjectSlugSettingsRouteRouteWithChildren =
  AuthedOrganizationSlugProjectSlugSettingsRouteRoute._addFileChildren(
    AuthedOrganizationSlugProjectSlugSettingsRouteRouteChildren,
  )

interface AuthedOrganizationSlugProjectSlugRouteRouteChildren {
  AuthedOrganizationSlugProjectSlugSettingsRouteRoute: typeof AuthedOrganizationSlugProjectSlugSettingsRouteRouteWithChildren
  AuthedOrganizationSlugProjectSlugIndexRoute: typeof AuthedOrganizationSlugProjectSlugIndexRoute
  AuthedOrganizationSlugProjectSlugContentDraftIdRoute: typeof AuthedOrganizationSlugProjectSlugContentDraftIdRoute
  AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute: typeof AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute
  AuthedOrganizationSlugProjectSlugContentIndexRoute: typeof AuthedOrganizationSlugProjectSlugContentIndexRoute
  AuthedOrganizationSlugProjectSlugLinksIndexRoute: typeof AuthedOrganizationSlugProjectSlugLinksIndexRoute
  AuthedOrganizationSlugProjectSlugStrategiesIndexRoute: typeof AuthedOrganizationSlugProjectSlugStrategiesIndexRoute
}

const AuthedOrganizationSlugProjectSlugRouteRouteChildren: AuthedOrganizationSlugProjectSlugRouteRouteChildren =
  {
    AuthedOrganizationSlugProjectSlugSettingsRouteRoute:
      AuthedOrganizationSlugProjectSlugSettingsRouteRouteWithChildren,
    AuthedOrganizationSlugProjectSlugIndexRoute:
      AuthedOrganizationSlugProjectSlugIndexRoute,
    AuthedOrganizationSlugProjectSlugContentDraftIdRoute:
      AuthedOrganizationSlugProjectSlugContentDraftIdRoute,
    AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute:
      AuthedOrganizationSlugProjectSlugStrategiesStrategyIdRoute,
    AuthedOrganizationSlugProjectSlugContentIndexRoute:
      AuthedOrganizationSlugProjectSlugContentIndexRoute,
    AuthedOrganizationSlugProjectSlugLinksIndexRoute:
      AuthedOrganizationSlugProjectSlugLinksIndexRoute,
    AuthedOrganizationSlugProjectSlugStrategiesIndexRoute:
      AuthedOrganizationSlugProjectSlugStrategiesIndexRoute,
  }

const AuthedOrganizationSlugProjectSlugRouteRouteWithChildren =
  AuthedOrganizationSlugProjectSlugRouteRoute._addFileChildren(
    AuthedOrganizationSlugProjectSlugRouteRouteChildren,
  )

interface AuthedOrganizationSlugRouteRouteChildren {
  AuthedOrganizationSlugProjectSlugRouteRoute: typeof AuthedOrganizationSlugProjectSlugRouteRouteWithChildren
  AuthedOrganizationSlugIndexRoute: typeof AuthedOrganizationSlugIndexRoute
  AuthedOrganizationSlugSettingsTeamRoute: typeof AuthedOrganizationSlugSettingsTeamRoute
}

const AuthedOrganizationSlugRouteRouteChildren: AuthedOrganizationSlugRouteRouteChildren =
  {
    AuthedOrganizationSlugProjectSlugRouteRoute:
      AuthedOrganizationSlugProjectSlugRouteRouteWithChildren,
    AuthedOrganizationSlugIndexRoute: AuthedOrganizationSlugIndexRoute,
    AuthedOrganizationSlugSettingsTeamRoute:
      AuthedOrganizationSlugSettingsTeamRoute,
  }

const AuthedOrganizationSlugRouteRouteWithChildren =
  AuthedOrganizationSlugRouteRoute._addFileChildren(
    AuthedOrganizationSlugRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedOrganizationSlugRouteRoute: typeof AuthedOrganizationSlugRouteRouteWithChildren
  AuthedInviteInvitationIdRoute: typeof AuthedInviteInvitationIdRoute
  AuthedOnboardingIndexRoute: typeof AuthedOnboardingIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedOrganizationSlugRouteRoute:
    AuthedOrganizationSlugRouteRouteWithChildren,
  AuthedInviteInvitationIdRoute: AuthedInviteInvitationIdRoute,
  AuthedOnboardingIndexRoute: AuthedOnboardingIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
