packages:
  - apps/*
  - packages/*
  - tooling/*

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - aws-sdk
  - core-js-pure
  - esbuild

nodeLinker: hoisted
linkWorkspacePackages: true
