/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog/rss[.]xml'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as ApiBlogSearchRouteImport } from './routes/api/blog/search'

const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BlogRouteRoute,
} as any)
const ApiBlogSearchRoute = ApiBlogSearchRouteImport.update({
  id: '/api/blog/search',
  path: '/api/blog/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/api/blog/search': typeof ApiBlogSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog': typeof BlogIndexRoute
  '/api/blog/search': typeof ApiBlogSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/blog/$': typeof BlogSplatRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/': typeof BlogIndexRoute
  '/api/blog/search': typeof ApiBlogSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/blog/'
    | '/api/blog/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/$' | '/blog/rss.xml' | '/blog' | '/api/blog/search'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/blog/$'
    | '/blog/rss.xml'
    | '/blog/'
    | '/api/blog/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  ApiBlogSearchRoute: typeof ApiBlogSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/api/blog/search': {
      id: '/api/blog/search'
      path: '/api/blog/search'
      fullPath: '/api/blog/search'
      preLoaderRoute: typeof ApiBlogSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteRouteChildren {
  BlogSplatRoute: typeof BlogSplatRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSplatRoute: BlogSplatRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  ApiBlogSearchRoute: ApiBlogSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
