/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinstonRouteImport } from './routes/winston'
import { Route as AaronRouteImport } from './routes/aaron'
import { Route as IndexRouteImport } from './routes/index'

const WinstonRoute = WinstonRouteImport.update({
  id: '/winston',
  path: '/winston',
  getParentRoute: () => rootRouteImport,
} as any)
const AaronRoute = AaronRouteImport.update({
  id: '/aaron',
  path: '/aaron',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aaron': typeof AaronRoute
  '/winston': typeof WinstonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aaron': typeof AaronRoute
  '/winston': typeof WinstonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aaron': typeof AaronRoute
  '/winston': typeof WinstonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aaron' | '/winston'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aaron' | '/winston'
  id: '__root__' | '/' | '/aaron' | '/winston'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AaronRoute: typeof AaronRoute
  WinstonRoute: typeof WinstonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winston': {
      id: '/winston'
      path: '/winston'
      fullPath: '/winston'
      preLoaderRoute: typeof WinstonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aaron': {
      id: '/aaron'
      path: '/aaron'
      fullPath: '/aaron'
      preLoaderRoute: typeof AaronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AaronRoute: AaronRoute,
  WinstonRoute: WinstonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
