name: Deploy to Trigger.dev (Prod)

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./tooling/github/setup
    
      - name: Prepare secrets
        id: prepare_secrets
        uses: ./tooling/github/prepare-secrets
        with:
            env_path: .env.production

      - name: Deploy to Trigger.dev
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: |
          pnpm run task:deploy